import '@/styles/output.css';
import '@/styles/global.css';
import { RoleProvider } from '@/components/RoleProvider/RoleProvider';
import AuthGuard from '@/components/AuthGuard/AuthGuard';

export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ru">
      <body>
        <RoleProvider>
          <AuthGuard>{children}</AuthGuard>
        </RoleProvider>
      </body>
    </html>
  );
}